#!/bin/bash
# Quick deploy script for Vercel

echo "🚀 Festive Playlist Architect - Deployment Helper"
echo ""
echo "Step 1: Create a GitHub repository"
echo "   → Go to: https://github.com/new"
echo "   → Name it: festive-playlist-architect"
echo "   → Don't initialize with README"
echo "   → Click 'Create repository'"
echo ""
echo "Step 2: After creating the repo, run these commands:"
echo ""
echo "   git remote add origin https://github.com/YOUR_USERNAME/festive-playlist-architect.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "   (Replace YOUR_USERNAME with your GitHub username)"
echo ""
echo "Step 3: Deploy to Vercel"
echo "   → Go to: https://vercel.com"
echo "   → Sign in with GitHub"
echo "   → Click 'Add New...' → 'Project'"
echo "   → Select your repository"
echo "   → Click 'Deploy'"
echo ""
echo "Step 4: After deployment, you'll get a URL like:"
echo "   https://festive-playlist-architect.vercel.app"
echo ""
echo "Step 5: Add environment variables in Vercel:"
echo "   → Go to Settings → Environment Variables"
echo "   → Add all variables from .env.local"
echo "   → Update NEXTAUTH_URL to your Vercel URL"
echo ""
echo "Step 6: Update Spotify redirect URI:"
echo "   → Add: https://your-app.vercel.app/api/auth/callback/spotify"
echo ""

